# Generated by Django 3.1.3 on 2020-11-04 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_auto_20201104_0940'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='credential',
            name='user_group',
            field=models.ManyToManyField(blank=True, null=True, to='accountapp.UserGroup'),
        ),
    ]
