# Generated by Django 3.1.3 on 2020-11-06 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_auto_20201105_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='creater',
            new_name='creator',
        ),
    ]
