# Generated by Django 3.1.3 on 2020-11-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0006_auto_20201106_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
